import { AxisConfig } from "../axis/AxisConfig";
import { ColorScaleConfigInterface } from "../color/ColorScaleConfig";
import { EntitySelectionMode, FacetStrategy, SeriesColorMap, SeriesStrategy } from "../core/GrapherConstants";
import { ComparisonLineConfig } from "../scatterCharts/ComparisonLine";
import { TooltipProps } from "../tooltip/TooltipProps";
import { OwidTable } from "../../coreTable/OwidTable";
import { ColumnSlug } from "../../coreTable/CoreTableConstants";
import { AxisConfigInterface } from "../axis/AxisConfigInterface";
import { ColorSchemeName } from "../color/ColorConstants";
import { EntityName } from "../../coreTable/OwidTableConstants";
import { SelectionArray } from "../selection/SelectionArray";
import { Annotation } from "../../clientUtils/owidTypes";
export interface ChartManager {
    baseFontSize?: number;
    table: OwidTable;
    transformedTable?: OwidTable;
    isSelectingData?: boolean;
    startSelectingWhenLineClicked?: boolean;
    isExportingtoSvgOrPng?: boolean;
    isRelativeMode?: boolean;
    comparisonLines?: ComparisonLineConfig[];
    hideLegend?: boolean;
    tooltip?: TooltipProps;
    useTimelineDomains?: boolean;
    baseColorScheme?: ColorSchemeName;
    invertColorScheme?: boolean;
    compareEndPointsOnly?: boolean;
    zoomToSelection?: boolean;
    matchingEntitiesOnly?: boolean;
    colorScale?: ColorScaleConfigInterface;
    yAxis?: AxisConfig;
    xAxis?: AxisConfig;
    yAxisConfig?: AxisConfigInterface;
    xAxisConfig?: AxisConfigInterface;
    addCountryMode?: EntitySelectionMode;
    yColumnSlug?: ColumnSlug;
    yColumnSlugs?: ColumnSlug[];
    xColumnSlug?: ColumnSlug;
    sizeColumnSlug?: ColumnSlug;
    colorColumnSlug?: ColumnSlug;
    selection?: SelectionArray | EntityName[];
    selectedColumnSlugs?: ColumnSlug[];
    yColumnSlugsInSelectionOrder?: ColumnSlug[];
    seriesColorMap?: SeriesColorMap;
    hidePoints?: boolean;
    lineStrokeWidth?: number;
    hideXAxis?: boolean;
    hideYAxis?: boolean;
    facetStrategy?: FacetStrategy;
    seriesStrategy?: SeriesStrategy;
    annotation?: Annotation;
    resetAnnotation?: () => void;
}
//# sourceMappingURL=ChartManager.d.ts.map