import { GrapherExports } from "../baker/GrapherBakingUtils";
import { Country } from "../clientUtils/countries";
import { CountryProfileSpec } from "../site/countryProfileProjects";
export declare const renderToHtmlPage: (element: any) => string;
export declare const renderChartsPage: () => Promise<string>;
export declare const renderCovidPage: () => string;
export declare const renderPageBySlug: (slug: string) => Promise<string>;
export declare const renderPreview: (postId: number) => Promise<string>;
export declare const renderMenuJson: () => Promise<string>;
export declare const renderFrontPage: () => Promise<string>;
export declare const renderDonatePage: () => string;
export declare const renderSubscribePage: () => string;
export declare const renderBlogByPageNum: (pageNum: number) => Promise<string>;
export declare const renderSearchPage: () => string;
export declare const renderNotFoundPage: () => string;
export declare function makeAtomFeed(): Promise<string>;
export declare const entriesByYearPage: (year?: number | undefined) => Promise<string>;
export declare const pagePerVariable: (variableId: number, countryName: string) => Promise<string>;
export declare const feedbackPage: () => string;
export declare const renderCountryProfile: (profileSpec: CountryProfileSpec, country: Country, grapherExports?: GrapherExports | undefined) => Promise<string>;
export declare const countryProfileCountryPage: (profileSpec: CountryProfileSpec, countrySlug: string) => Promise<string>;
export declare const flushCache: () => void | undefined;
//# sourceMappingURL=siteRenderers.d.ts.map